version: '3.8'

services:
  web:
    container_name: django_container
    build: .
    command: python3 /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      - .env
    restart: unless-stopped

  # PostgreSQL veritabanı servisi
  db:
    container_name: postgres_container
    image: postgres:14
    volumes:
      - ~/Desktop/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    env_file:
      - .env
    restart: unless-stopped

  # Tailwind CSS için npm servisi
  # npm:
  #   container_name: tailwind_container
  #   image: node:14-slim
  #   working_dir: /code/frontend
  #   command: npm run watch
  #   volumes:
  #     - ./frontend:/code/frontend
  #   depends_on:
  #     - web